---
title: "Spearman correlation plot"
author: "Chunguang Lai"
date: "2022-01-29"
output:	html_document
keep_md: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, error = TRUE}
# https://r-coder.com/correlation-plot-r/
# Data generation
set.seed(1)

x=read.csv2("E:/google\ drive/Thesis/data/drugcell_related/data/sample/split52/drugcell_test1.txt",header=FALSE,sep="\t")
x=as.numeric(x[[3]])
y=as.numeric(read.csv2("E:/google\ drive/Thesis/data/drugcell_related/data/predict/predict1/Result_sample/drugcell.predict",header=FALSE,sep="\t")[[1]])
# names(x) <- NULL
# names(y) <- NULL
# x <- 1:100
# y <- x + rnorm(100, mean = 0, sd = 15)
# Creating the plot
plot(x[1:100], y[1:100], pch = 19, col = "lightblue",
     xlim=c(0,1.5))
plot(x, y, pch = 19, col = "lightblue")

# Regression line
abline(lm(y ~ x), col = "red", lwd = 3)
# text(paste("Correlation:", text1), x=85, y=25)
text1=round(cor(x, y, method = "spearman"),2)
mtext(paste("Spearman rho:", text1), side=3)

# Pearson correlation


# https://rpubs.com/aaronsc32/spearman-rank-correlation
# cor.test(x, y, method = 'spearman')
```


